### PR TITLE
Adjustment(CFG): Added Pizza Shop MLO

### PR DESCRIPTION
**Pull request by Savage912-Official**
Added Pizza Shop MLO to CFG as requested in a suggestion.

### CODE REVIEW

**Comment by ChangyBoi** [comment]
I know a lot of people wouldnt be happy with this because of how close to legion it is. We already have 2 massive MLO such as pillbox and MRPD. If we can find a pizza MLO that isn't near legion I'm all for it but legion just needs to be kept as clear as possible IMO

**Comment by Savage912-Official** [comment]
> I know a lot of people wouldnt be happy with this because of how close to legion it is. And could potentially worsen performance in that area, We already have 2 massive MLO such as pillbox and MRPD. If we can find a pizza MLO that isn't near legion I'm all for it but legion just needs to be kept as clear as possible IMO

Yeah I told mini we could get gabz which is on popular street but he said to just do this one for now so I did. I do think we should change to a different one at some point though.

**Comment by minipunch** [comment]
Let's just go ahead and get Gabz' and we can add it instead

**Comment by Savage912-Official** [comment]
> Let's just go ahead and get Gabz' and we can add it instead

Alright only issue is it’s through tebex so the FiveM account associated with the server license key has to buy it from him or it won’t allow us to use it.

**Comment by minipunch** [comment]
outside textures seem to be flickering badly and makes it look bad

even 'cleared server cache'

**Pull request closed without merging**
