### PR TITLE
Removed unused maps

### PR DESCRIPTION
**Pull request by Zeeroqt**
- removed maps that are not used anymore
- removed fightclub blip

### CODE REVIEW

**Review by minipunch — CHANGES_REQUESTED** [review]
U trying to sneak in ur chat ui change too ???

**Comment by Zeeroqt** [comment]
wait wtf, how tf did that get there. LMFAO I can make a new pr unless u can reject the ui change in this pr and accept the server.cfg stuff

**Comment by minipunch** [comment]
> wait wtf, how tf did that get there. LMFAO I can make a new pr unless u can reject the ui change in this pr and accept the server.cfg stuff

I can't reject individual files, so u'll have to make a new one

Most likely it is because u made this new branch on top of ur ui changes instead of on top of the latest version of `public-server`

**Comment by Zeeroqt** [comment]
yeah that’s what happened. I’ll make a new pr once I’m home

**Pull request closed without merging**
