### PR TITLE
New Trucks and a Trailer

### PR DESCRIPTION
**Pull request by Rezitoo**
Added four new trucks to the store, Boosting and Racing. Added a new trailer to the store

### CODE REVIEW

**Comment by minipunch** [comment]
have to also update the vehicle submodule right ??

if u aren't sure how u should ask someone how to make ur PR also update the submodule so I don't have to manually

**Comment by Rezitoo** [comment]
Was working on it last night before I passed out, almost got it figured out

**Comment by Rezitoo** [comment]
> have to also update the vehicle submodule right ??
> 
> if u aren't sure how u should ask someone how to make ur PR also update the submodule so I don't have to manually

Has been pushed with @Urbaniized  cx75 update

**Review by minipunch — APPROVED** [review]

**Comment by minipunch** [comment]
Can u resolve the merge conflicts for me plz

**Comment by Rezitoo** [comment]
It won't let me since I don't have write access

**Comment by minipunch** [comment]
> It won't let me since I don't have write access

You should be able to resolve them on your branch which is in your fork of the repo which u do have perms for

**Comment by Rezitoo** [comment]
After updating and syncing still couldn't find the conflict so removed them from the racing tablet all together in attempt to figure it out.

**Comment by minipunch** [comment]
Wait lol I don't think we want to remove those...

Can u just like... add them back now and see if it works I guess...

**Comment by Rezitoo** [comment]
I just cannot for the life of me find the conflict. In any files on either of my forks

**Review by minipunch — APPROVED** [review]

**Pull request merged**
