### PR TITLE
Vehicle Boosting

### PR DESCRIPTION
**Pull request by DatBoiWeep**
**Testing Status**
Completed - Thanks to Staff, Repo Contributors, Testing Group, and other volunteers for helping out and ensuring functionality is good.

**Config files**
config/server.lua -- Check line 33 for explanations 
config/client.lua
config/shared.lua -- Consists of where vehicles / peds spawn + delivery locations

**Video Preview**
https://www.youtube.com/watch?v=OBDsp0DNhlg

**RAHE Boosting**
https://forum.cfx.re/t/paid-rahe-boosting-system-esx-qb-custom/4858796

**Additions**
- Ability to boost vehicle range from "D" Class to "S" Class.
- "A" and "S" Classes require extra items to access 👀 
- Purchase items from the tablet shop and pick them up at a specific location
- Buy out a contract and earn the car for yourself when successfully completing all hacks + delivery 🚗  
- "S" class vehicles surprise. No one likes thieves taking their luxurious cars 😡 
- Leaderboard / History / Profile Changing
- Police receive 911 calls and active locations with GPS-enabled vehicles ⚠️
- Added `isVinScratched` field for vehicles successfully earned from boosting
    - [Support for future Fake License Plates and Vin Searching for Police]

**Changes**
- Removed police/civ access to hotwire/slimjim/lockpick A or S class **boost** vehicles.
- Added images for new items
- Added oxymsql
- Added new illegal items to the black-market and legal items to the general store

**Sneak Peaks**
image
image
image
image
image
image

### CODE REVIEW

**Comment by minipunch** [comment]
Before I look any further can u just make sure u tokenize the server reward events if possible for me if u haven't already

**Comment by DatBoiWeep** [comment]
> Before I look any further can u just make sure u tokenize the server reward events if possible for me if u haven't already

I don't believe it's in the public files, but I have asked their support if there is a way to call the events so we can add our spicy tokenizer

**Comment by minipunch** [comment]
how do u open the tablet lol

**Comment by minipunch** [comment]
any manual steps for me to install??

like running sql scripts or smth?

**Review by minipunch — APPROVED** [review]

**Pull request merged**
