### PR TITLE
Fixed issue with a 911 call

### PR DESCRIPTION
**Pull request by DatBoiWeep**
Suspicious injury calls were not showing up. `.dropEvidence` kept returning `nil` for some reason and couldn't figure it out. So as a temp fix, simply just made a function for suspicious calls to display true if sussy.

### CODE REVIEW

**Review by minipunch — APPROVED** [review]
👍

**Comment by minipunch** [comment]
Do we know if this has been working or not just to be sure on live ? @DatBoiWeep

**Comment by DatBoiWeep** [comment]
Yes sir and she works like a charm

**Comment by DatBoiWeep** [comment]
image

**Comment by minipunch** [comment]
Niceeee

**Pull request merged**
