### PR TITLE
New Police bike

### PR DESCRIPTION
**Pull request by Urbaniized**

### CODE REVIEW

**Comment by minipunch** [comment]
Looks like the PR has a bunch of unrelated changes, plz fix

**Comment by Urbaniized** [comment]
> Looks like the PR has a bunch of unrelated changes, plz fix

Not sure which changes you are referring to. `1200RT` was the old bike name, `polbike3` is the new one

**Comment by Urbaniized** [comment]
> > Looks like the PR has a bunch of unrelated changes, plz fix
> 
> Not sure which changes you are referring to. `1200RT` was the old bike name, `polbike3` is the new one

I just changed all the references for the old bike to the new bike

**Comment by Urbaniized** [comment]
> > > Looks like the PR has a bunch of unrelated changes, plz fix
> > 
> > 
> > Not sure which changes you are referring to. `1200RT` was the old bike name, `polbike3` is the new one
> 
> Oh I see
> 
> I guess the only unrelated change is the change to `custom_maps` then, right ?

Not sure how that got included in that lol but it's showing 0 changes on the maps

**Review by minipunch — APPROVED** [review]

**Pull request merged**
