### PR TITLE
Benny's, LaMesa & Atomic ATM's

### PR DESCRIPTION
**Pull request by Urbaniized**
Added ATM's for the MLOs

### CODE REVIEW

**Review by minipunch — APPROVED** [review]

**Review by minipunch — CHANGES_REQUESTED** [review]
Not sure editing gabz' maps is a good idea

Probably gonna end up losing them in the next update

**Comment by Urbaniized** [comment]
It's just the YTYP which is just interior props, doesn't change anything about the model it self. Gabz leaves it un-encrypted so people can edit it

**Comment by minipunch** [comment]
> It's just the YTYP which is just interior props, doesn't change anything about the model it self. Gabz leaves it un-encrypted so people can edit it

Still might end up losing it in an update since I have to drag and drop everything over lol

**Comment by Urbaniized** [comment]
I keep backups of them lol, it's not hard to add the extra props. I can see if I can get the additional props on a new file that is not gabz

**Comment by Urbaniized** [comment]
Oh I also updated some of the graffiti but that's not hard either

**Review by minipunch — APPROVED** [review]

**Pull request merged**
