### PR TITLE
BOATS!

### PR DESCRIPTION
**Pull request by Rezitoo**
Now you can buy a boat trailer and a addon boat, attach the boat to the trailer then detach it at another spot! easy to add new boats/trailers in the future as well as the default boat trailer

### CODE REVIEW

**Comment by minipunch** [comment]
any time u add a new script it would be good if u can show a photo of the `resmon` output for it when idling to make sure it doesn't need to be optimized plz

**Comment by Rezitoo** [comment]
Got you, I'll do that tomorrow

**Comment by Rezitoo** [comment]
@minipunch [https://i.imgur.com/MPcLGgL.png](url) Like this?

**Comment by minipunch** [comment]
Ye looks good

**Review by minipunch — APPROVED** [review]

**Pull request merged**
