### PR TITLE
update(PoliceHeli): New & Improved Script

### PR DESCRIPTION
**Pull request by Savage912-Official**
New and Improved Heli Script (More Optimized & More Features)

- Camera (Has Night & Thermal Vision) (**Key:** E | **Themal/Night Vision Key**: Right Mouse Button)
- Heli Seatbelt (**Key:** B)
- Hovering System (For Heli Stabilization) (**Key:** J | **Super Hover Key:** G)
- Help Display (Shows Controls / Info) (**Key:** L)

### CODE REVIEW

**Comment by minipunch** [comment]
Where u get it from ?

**Comment by Savage912-Official** [comment]
Yeah I sent to him in dms

**Comment by minipunch** [comment]
When u say it is more 'optimized', how so ?

This is the idle time for the current script on live:

**Comment by minipunch** [comment]
idle time in heli with cam running is:

**Comment by minipunch** [comment]
So it is a bit more optimized I guess at idle, the new one looks like it idles at even less: `0.00` which is nice

**Comment by minipunch** [comment]
So now:

1) why the extra/separate seat belt system, why not use the one we have now since it seems to function in the polmav already too, not sure if we need to add it to others or what?

2) think u can add like a little help text that says 'press L for help' when u get into a compatible vehicle (one with a helicam)

**Review by minipunch — CHANGES_REQUESTED** [review]
see comment

**Comment by Savage912-Official** [comment]
> see comment

Completed

**Review by minipunch — APPROVED** [review]
nice

**Pull request merged**
