### PR TITLE
MRPD Modifications

### PR DESCRIPTION
**Pull request by DatBoiWeep**
Removes Gabz MRPD MLO, adds old MRPD.

### CODE REVIEW

**Comment by minipunch** [comment]
1. Can you fix the merge conflict
2. Are u sure most people want this?

**Comment by DatBoiWeep** [comment]
> 1. Can you fix the merge conflict
> 
>     2. Are u sure most people want this?

1. Si

2. Well, this will hopefully help with some of the lag issues that occur in Legion Square because players have to render the big MLOs like Gabz_MRPD and Hospital. Plus. Nostalgia :)

**Comment by minipunch** [comment]
I don't even remember what the old one looked like

**Comment by ChangyBoi** [comment]
> I don't even remember what the old one looked like, wanna show some pics

https://www.gta5-mods.com/maps/community-mission-row-pd

**Comment by DatBoiWeep** [comment]
image
image
image
image
image
image

**Comment by ChangyBoi** [comment]
BEST MRPD

**Comment by DatBoiWeep** [comment]
This is where Senior Trooper Chris Cortega made his way to Director of Emergency Services 🤧 🤧 🤧 🤧

**Review by minipunch — APPROVED** [review]

**Pull request merged**
