### PR TITLE
Update Mechanic repair time, install time and lvl 3 requirement

### PR DESCRIPTION
**Pull request by Crownapple**
I have seen a few suggestions on reducing the time on repairs and install. Also, Have seen suggestions on lowering the the lvl 3 requirement but I believe that some people have got to lvl 3 by getting 500+ repairs so I believe it should be lowered by 50

### CODE REVIEW

**Comment by Rezitoo** [comment]
Wasn't this already lowered to 350?

**Comment by Crownapple** [comment]
> Wasn't this already lowered to 350?

I mean I just re cloned the github and I have also checked the main file on github and its still have 500

**Comment by Rezitoo** [comment]
> > Wasn't this already lowered to 350?
> 
> I mean I just re cloned the github and I have also checked the main file on github and its still have 500

In server at 350 repairs you get level 3

**Comment by Crownapple** [comment]
You shouldn’t

**Comment by Rezitoo** [comment]
> You shouldn’t

Yes you should https://github.com/minipunch/usarealismrp-fxserver/commit/3a904b3c04e262b069a947c80e2e32e2b5e2f0c6

**Pull request closed without merging**
