### PR TITLE
Updates sv_jail.lua

### PR DESCRIPTION
**Pull request by Khajit71**
Added the 2 new charges innit.
*TESTED*

### CODE REVIEW

**Comment by maxgestic** [comment]
I belive they are federal codes to revoke firearm permit if someone is charged with them @minipunch

**Comment by Khajit71** [comment]
As I have stated in the dev chat, and also as @maxgestic said, they are federal codes for the following:

`18 U.S. Code § 921` - Possession of Illegal gun parts, explosives | 15 months & $500 fine per part
`26 U.S. Code § 5861` - Manufacturing of weapons or explosives | 20 months & $3,500 fine

Both of these charges are already added on the server, and people are able to get charged with them. Both of these charges are felony's too.

**Review by DatBoiWeep — APPROVED** [review]
weepers seal of approval

**Comment by minipunch** [comment]
> they are federal codes for the following:

Can you provide links on where u found this info

Cause when I searched it wasn't very obvious that's what it was

**Comment by Khajit71** [comment]
I couldn't find exact charges for this, and had to improvise. They were sent to me in the DOJ discord, and I wrote the definitions and times/fines. We are California BASED, hence why I used these as I couldn't find exact ones @minipunch

**Comment by minipunch** [comment]
@Khajit71 

For the first one, change it to section `922` instead of `921` since `922` contains the unlawful acts and 921 is just 'definitions'

And for explosives you should prob use this one instead: 18 U.S. Code § 842 (https://www.law.cornell.edu/uscode/text/18/842)

That deals with unlawful (includes unlicensed) acts dealing with explosives

**Review by minipunch — CHANGES_REQUESTED** [review]
see comment

**Comment by Khajit71** [comment]
@minipunch updated it, see 2nd commit from today

**Review by minipunch — APPROVED** [review]

**Pull request merged**
