### PR TITLE
Added xmas map update by NVE

### PR DESCRIPTION
**Pull request by DatBoiWeep**
NVE provides a free xmas update that adds Christmas trees, snowmen, and additional features across the map. Just in time for the holidays :)

Checked a few MLOs in the areas to ensure no possible conflicts; seems to work fine and does not negatively affect anything when roaming the common areas.

### CODE REVIEW

**Comment by maxgestic** [comment]
Dis some good shit

**Comment by maxgestic** [comment]
Means we can ice skate cos i think this has both the alamo sea frozen and the mirror park lake

**Review by maxgestic — CHANGES_REQUESTED** [review]
I have made a pull request to @DatBoiWeep to also add frozen lakes wait until that is pushed to approve this

**Comment by DatBoiWeep** [comment]
> I have made a pull request to @DatBoiWeep to also add frozen lakes wait until that is pushed to approve this

Done 👌

**Comment by minipunch** [comment]
WHERE MY PREVIEW PICS @ ⁉️

**Review by minipunch — APPROVED** [review]

**Pull request merged**
