### PR TITLE
New Police Car

### PR DESCRIPTION
**Pull request by Urbaniized**

### CODE REVIEW

**Comment by maxgestic** [comment]
I know you didn't just make a pr for a police lambo right?

**Comment by minipunch** [comment]
😂😂

**Comment by maxgestic** [comment]
Actually it be pog but like wow, but noone will be allowed to drive it except like 2 command staff

**Comment by ChangyBoi** [comment]
This is actual POG hehe

**Comment by minipunch** [comment]
don't wanna hear anyone complain about how unrealistic something is anymore 😂

**Review by minipunch — APPROVED** [review]

**Review by minipunch — APPROVED** [review]

**Pull request merged**
