### PR TITLE
feat: Block nui_devtools

### PR DESCRIPTION
**Pull request by Savage912-Official**
More info about this posted in our group chat.

### CODE REVIEW

**Comment by maxgestic** [comment]
Plz add to Allowlist ty

**Comment by Savage912-Official** [comment]
> Plz add to Allowlist ty

Send your steam to me here or in dms and I’ll put you on it.

**Comment by maxgestic** [comment]
https://steamcommunity.com/id/sirchainsmokergollum/

**Comment by minipunch** [comment]
What is the effect of this exactly?

Cause I tried it but I was still able to access the dev tool page

**Review by minipunch — APPROVED** [review]

**Pull request merged**
