### PR TITLE
feat(Vehicles): Wheel Fitment

### PR DESCRIPTION
**Pull request by Savage912-Official**
Allows mechanics to adjust the wheel fitment on vehicles.

Make sure to import ae-fitment.sql

### CODE REVIEW

**Comment by minipunch** [comment]
So how do u use it exactly ?

**Comment by Savage912-Official** [comment]
When signed on as a mechanic you would go to one of the locations in the config and click E and the fitment menu will appear on the screen.

**Comment by minipunch** [comment]
hm I get this db error:

```SCRIPT ERROR in promise (unhandled rejection): Error: ae-fitment was unable to execute a query!
[      script:oxmysql] Field 'fitment' doesn't have a default value
[      script:oxmysql] INSERT INTO veh_fitment (plate) VALUES (?) ["KKBRUH"]```

maybe cuz i am using mysql v8? r u using v5?

**Comment by minipunch** [comment]
Yeah I get that error whenever I take it out of the garage
And nothing gets put into the DB
Also no save notification when I click save

**Comment by Savage912-Official** [comment]
Pretty much completed waiting for mini to try his sql edits in attempts to get it working on his end.

**Review by minipunch — APPROVED** [review]

**Pull request merged**
