### PR TITLE
Updated armoredtruck robberies

### PR DESCRIPTION
**Pull request by DatBoiWeep**
**Changes**
Updated minigames to allow backing out or provide max lives to kick you out of the terminal.
Updated 911 resource for `BankTruck` call

Items needed
- `Laptop` and `Blackhat USB Drive`
   - Now have a 1% to 7% chance of being destroyed upon usage
- `Armored Truck Bomb` to replace `sticky bomb` due to several complaints
   - Added longer timer to trucks to allow police response.
   - Loot earnings also changed + added rarity in other things
- Minigames adjusted to include lives and a timer to kick you out of the game
- Changed type of blip from `area` to `point`
- Increased timer on bomb to allow police response

**To Do**
- [x] Change explosive from Sticky Bomb to a new item
- [x] Add the new item to crafting / black market
- [x] Add new minigames
- [x] Adjust payout
- [x] Add more spawn locations for truck
- [x] Add variety loot depending on truck received
- [x] Change aggression of armed peds
- [x] Change locations of terminals

**Images**
image
image
image

### CODE REVIEW

**Comment by minipunch** [comment]
Status on this ?

**Comment by DatBoiWeep** [comment]
> Status on this ?

The owner broke something so I'm waiting for him to push the update to fix the minigames 💀

**Comment by DatBoiWeep** [comment]
No ETA yet sadge

**Comment by DatBoiWeep** [comment]
She's good to go chief. Let me know if any changes / adjustments are needed

**Comment by minipunch** [comment]
Why did u want to change the item from sticky bomb?

**Review by minipunch — APPROVED** [review]

**Pull request merged**
