### PR TITLE
Adjusted walkstyles

### PR DESCRIPTION
**Pull request by DatBoiWeep**
- Removed /walk flee due to abuse (From: Chang)

### CODE REVIEW

**Comment by ChangyBoi** [comment]
Best change ever

**Review by maxgestic — DISMISSED** [review]
Pog

**Review by maxgestic — APPROVED** [review]
Looks all good!

**Comment by minipunch** [comment]
BOO

I am only going to merge this since people probably don't often use flee

But I say BOO because removing functionality that could potentially be used is a LAZY FIX

**Review by minipunch — APPROVED** [review]

**Pull request merged**
