### PR TITLE
update(Rob/Search): ability to rob when person has hands up

### PR DESCRIPTION
**Pull request by Savage912-Official**
A player can now be robbed/searched if they have their hands up.

Tested and works

Issue: #1203 Completed

### CODE REVIEW

**Comment by minipunch** [comment]
Seems like it works pretty good

I would like to see it close the search interface if:
- [ ] the being robbed player puts their hands down
- [ ] the being robbed player has enough distance between him and the robber

to avoid any issues there

**Comment by Savage912-Official** [comment]
> Seems like it works pretty good
> 
> I would like to see it close the search interface if:
> 
> * [ ]  the being robbed player puts their hands down
> * [ ]  the being robbed player has enough distance between him and the robber
> 
> to avoid any issues there

Alright ill look into this

**Review by minipunch — CHANGES_REQUESTED** [review]
see comment

**Comment by Savage912-Official** [comment]
Awaiting mini to look into this (Said he would check it out in dms)

**Comment by minipunch** [comment]
How come you closed this @Savage912-Official ?

**Comment by Savage912-Official** [comment]
just temp closed to clear it out of the list for now until we get to it.

**Comment by minipunch** [comment]
> just temp closed to clear it out of the list for now until we get to it.

We can mark it as a 'draft' which means that it's in progress so we don't need to close it

**Review by minipunch — APPROVED** [review]

**Pull request merged**
