### PR TITLE
Added three store locations

### PR DESCRIPTION
**Pull request by Rezitoo**
These are pending the addition of the 24/7 interiors sent to mr chris :)

### CODE REVIEW

**Comment by minipunch** [comment]
Going to mark this as a draft now since we're waiting on I guess @DatBoiWeep  ?

**Comment by Rezitoo** [comment]
Yeah I sent him the interiors

**Review by DatBoiWeep — CHANGES_REQUESTED** [review]
Make sure to add the cameras to the `_securitycams` script. Right now the cameras don't exist so police won't be able to view them.

**Comment by DatBoiWeep** [comment]
@Rezitoo any update on this or do you need help with setting up the security cams

**Comment by Rezitoo** [comment]
> @Rezitoo any update on this or do you need help with setting up the security cams

Security cameras have me big confused,

**Comment by DatBoiWeep** [comment]
> > @Rezitoo any update on this or do you need help with setting up the security cams
> 
> Security cameras have me big confused,

lmao, I can show you how they are done when you get time

**Review by DatBoiWeep — APPROVED** [review]
Good to go on this bad boi stuff

**Comment by minipunch** [comment]
Can someone resolve the merge conflict plz

**Comment by DatBoiWeep** [comment]
> Can someone resolve the merge conflict plz

push it

**Comment by DatBoiWeep** [comment]
pls :)

**Review by DatBoiWeep — APPROVED** [review]

**Review by minipunch — APPROVED** [review]

**Pull request merged**
