### PR TITLE
MLO Changes

### PR DESCRIPTION
**Pull request by ChangyBoi**
Disabled
 - brofx_5
 - vinewood_house
 - int_weed
 - MilosStudio
 - lks_fight
 - BB blip
 - Processing spot BB
 - Fight club blip

Added
 - White Widow
 - Blip for WW
 - WW processing

### CODE REVIEW

**Comment by Zeeroqt** [comment]
You need to remove the fight club blip and u need to remove the location of best bud in the fire script

**Comment by ChangyBoi** [comment]
> You need to remove the fight club blip and u need to remove the location of best bud in the fire script

Blip was already disabled, just not in the list

Best buds is not part of the random fire that can start. At least from what I could tell looking at [fire] > firescript > Config.lua

**Comment by Zeeroqt** [comment]
image

**Comment by DatBoiWeep** [comment]
> 

Unsure what you mean by this. He did remove it per `resources/usa_map_blips/client.lua` on line edit 116

image

**Review by minipunch — APPROVED** [review]

**Pull request merged**
