### PR TITLE
Added new THF Block

### PR DESCRIPTION
**Pull request by DatBoiWeep**
Speak to Zeero#6969 regarding this update

**Review**
No collision issues for any nearby pre-existing MLOs

### CODE REVIEW

**Comment by minipunch** [comment]
@DatBoiWeep u able to resolve these conflicts for me plz

**Comment by minipunch** [comment]
@Zeeroqt @Khajit71 I assume u still want this in ?

**Comment by DatBoiWeep** [comment]
Conflicts resolved

**Comment by Khajit71** [comment]
correct @minipunch

**Review by minipunch — APPROVED** [review]

**Pull request merged**
