### PR TITLE
Gabz Vespucci Beach MLO

### PR DESCRIPTION
**Pull request by DatBoiWeep**
**Additions**
- Added new Gabz Vespucci Beach MLO
   - Stores available: groceries, liquor, masks, bikes, electronics, cafe, pharmacy, and more.
- Added Security Cameras | Camera ID : `vbeach`
- Added Shops (Bikes and Medical)
- Added Vacancy Shops
- Added Retro Arcade Machines

**Opportunities**
- Ability to customize shops, add vacancy shops for more RP
- Can request business locations to be added / modified

**Known Bugs**
- MLO conflicts with `int_yachtclub` which causes bad things in certain areas LOL

**Example**
image

**Map Trailer**
https://www.youtube.com/watch?v=dm9f7VCxcKM

### CODE REVIEW

**Comment by minipunch** [comment]
Hmm prob not worth pushing if it is conflicting with those interiors.....

**Review by minipunch — CHANGES_REQUESTED** [review]
would like to get the conflicting issue with the other MLO fixed before merging

**Comment by DatBoiWeep** [comment]
> would like to get the conflicting issue with the other MLO fixed before merging

Yeah, better off holding off on it. If possible @maxgestic , can you look into looking for the conflicts from the map MLOs?

Should be `int_yachtclub` and `cfx-gabz-vbeach`

**Comment by maxgestic** [comment]
Well if the collision file are encrypted somehow there won't be much I can do, but I'll take a look

**Comment by DatBoiWeep** [comment]
Going to close this for now - Will re-evaluate this at a later time :)

**Pull request closed without merging**
