### PR TITLE
feat(Mechanic): RGB Controller

### PR DESCRIPTION
**Pull request by Savage912-Official**
RGB Controller can be crafted by Level 3 Mechanics. To use it just use the RGB Controller item and you will be given lots of options for headlights / underglow animations and colors.

*You must have Xenon Lights & Underglow on your car for these options to work*

Underglow can now be toggled on / off via a keybind. The default keybind is G but can be changed in your FiveM keybind settings.

### CODE REVIEW

**Review by minipunch — CHANGES_REQUESTED** [review]
Getting this error in F8 when I restart usa_rp2 lol

**Comment by Savage912-Official** [comment]
> Getting this error in F8 when I restart usa_rp2 lol

What error? And I’ll be home sometime later today to fix it.

**Comment by minipunch** [comment]
![](https://i.imgur.com/6Vav0IV.png

**Comment by minipunch** [comment]
Looks dope !

Nice

**Review by minipunch — APPROVED** [review]

**Pull request merged**
