### PR TITLE
feat(Ammunation): Gun Ranges

### LINKED ISSUE #1557: try this cool gun range script
https://store.rcore.cz/package/4337823

from rcore so hopefully it's e z to implement as some of their other ones have been in the past

### PR DESCRIPTION
**Pull request by Savage912-Official**
closes #1557

### CODE REVIEW

**Comment by minipunch** [comment]
Can u resolve the merge conflicts for me please

**Review by minipunch — CHANGES_REQUESTED** [review]
Pretty nice

Can we just 1) raise the prices a bit to like 500 per gun to try them and 2) remove the $ from 2 lanes at each range so players can not use the script if they want to instead

**Comment by minipunch** [comment]
Also noticed in server console I am getting this error a bunch in a row:

```
[ script:usa_911calls] SCRIPT ERROR: @usa_911calls/server.lua:217: attempt to index a nil value (global 'rcore_gunrange')
[ script:usa_911calls] > handler (@usa_911calls/server.lua:217)
```

**Comment by Savage912-Official** [comment]
> Pretty nice
> 
> Can we just 1) raise the prices a bit to like 500 per gun to try them and 2) remove the $ from 2 lanes at each range so players can not use the script if they want to instead

Done

**Comment by Savage912-Official** [comment]
> Also noticed in server console I am getting this error a bunch in a row:
> 
> ```
> [ script:usa_911calls] SCRIPT ERROR: @usa_911calls/server.lua:217: attempt to index a nil value (global 'rcore_gunrange')
> [ script:usa_911calls] > handler (@usa_911calls/server.lua:217)
> ```

Fixed

**Review by minipunch — APPROVED** [review]
Nice, seems good

**Pull request merged**
