### PR TITLE
Added Plasma Kart

### LINKED ISSUE #1432: try this plasma kart "mario kart" script
https://forum.cfx.re/t/plasmakart-script-standalone/4790879

looks fire

### PR DESCRIPTION
**Pull request by Crownapple**
Plasma kart is where you can race with your friends in go karts. There is 2 mode regular and battle. Regular is where you guys just race, Battle is where you can race and sabotage your friends by laying spikes and there is boost as well.

CLOSES #1432

### CODE REVIEW

**Comment by minipunch** [comment]
I don't think we need the `PataModElevatorV2Lock` one 

It worked fine without that one for me so let's remove that for now since I don't think it's needed?

**Comment by Savage912-Official** [comment]
> I don't think we need the `PataModElevatorV2Lock` one
> 
> It worked fine without that one for me so let's remove that for now since I don't think it's needed?

Yeah, when we tested last night we didn't use that not sure why it got pushed.

**Comment by Crownapple** [comment]
> I don't think we need the `PataModElevatorV2Lock` one
> 
> It worked fine without that one for me so let's remove that for now since I don't think it's needed?

Fixed

**Comment by Crownapple** [comment]
closes #1432

**Comment by minipunch** [comment]
> closes #1432

fyi this needs to go in the PR description

**Review by minipunch — CHANGES_REQUESTED** [review]
@Crownapple needs to work with @ChangyBoi and or @DatBoiWeep to get the clothing component numbers right here for this script

**Pull request closed without merging**
