### PR TITLE
update item images in images folder

### PR DESCRIPTION
**Pull request by kian969**

### CODE REVIEW

**Comment by kian969** [comment]
I **THINK** this is a way around that "Uploads are disabled" thing but I'm not sure...

**Comment by kian969** [comment]
87 files uploaded to repace old Imgur links and reflect bar and food updates

**Comment by minipunch** [comment]
Did you make sure to name the pngs the same as the ones defined in your #2335 PR?

**Comment by kian969** [comment]
> Did you make sure to name the pngs the same as the ones defined in your #2335 PR?

Yes! As I copied the imgur link, I named the file and downloaded it, then replaced the file name in #2335 with the file name I had just downloaded.  So in response to this it should be exactly the same!

**Review by minipunch — APPROVED** [review]

**Pull request merged**
