### PR TITLE
Added charges to /jail

### PR DESCRIPTION
**Pull request by Rezitoo**
Made some charges felonies

### CODE REVIEW

**Comment by minipunch** [comment]
Don't think 23109(b) AKA speed contest is usually charged as a felony, it's generally a misdemeanor here in CA

**Comment by Rezitoo** [comment]
Yeah when I looked it up (Street Racing) is a felony in CA which is why I added (b) to the law book. Unfortunately the only way to revoke a license when arresting someone for illegal street racing is to make it a felony

**Comment by minipunch** [comment]
I think it would only be charged as a felony if u crashed / hurt someone

And really you don't just lose your license for a 'street racing' ticket either

The DMV has a 'point' system though and if you have enough points basically or smth like that you can have it suspended

I'd like to get that system added

Cause it also usually raises insurance prices and crims will LOVE that 😂

**Review by minipunch — CHANGES_REQUESTED** [review]
see comment

**Comment by Rezitoo** [comment]
Alright that works, will delete this and wait to give points for it lmaooo

**Pull request closed without merging**
