### PR TITLE
New chatbox for usa

### PR DESCRIPTION
**Pull request by Zeeroqt**
- New UI 
- New Font
- Cool fading in transition when opening chat box.
- Preview: https://streamable.com/5yk3m8

### CODE REVIEW

**Comment by minipunch** [comment]
bruh it gotta have chat command suggestions at minimum

**Comment by minipunch** [comment]
would be ideal if we could make it optional so people can use either (or 'opt in' to try it)

**Comment by Zeeroqt** [comment]
> would be ideal if we could make it optional so people can use either (or 'opt in' to try it)

huh

**Comment by minipunch** [comment]
> > would be ideal if we could make it optional so people can use either (or 'opt in' to try it)
> 
> huh

u know

just in case some people hate it and want the old one

**Comment by Zeeroqt** [comment]
oh um i mean i can see what we can do or get a vote

**Pull request closed without merging**
